### ISSUE TITLE
Add LinkedIn profile picture if availible

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#21]

**Comment by edwinindrajayas** [comment]
I think it's not feasible,
because first of all, we need authorization which has a limited API call,
and we can only see images, if given permission by the user.

https://docs.microsoft.com/id-id/linkedin/shared/integrations/people/profile-api?context=linkedin/consumer/context#retrieve-other-members-profile

**Comment by mshd** [comment]
Yes I saw that API, ok fine, if there's no other way
